DROP SEQUENCE PER_IDENTIFICATION_SEQ;
DROP SEQUENCE PER_PERSON_DETAIL_SEQ;
--DROP SEQUENCE PER_PERSON_STATUS_SEQ;
DROP TABLE per_person  CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE per_person_seq;
DROP TABLE per_person_detail  CASCADE CONSTRAINTS PURGE;
DROP TABLE per_identification  CASCADE CONSTRAINTS PURGE;
