DROP SEQUENCE PER_GENDER_SEQ;
DROP TABLE PER_GENDER CASCADE CONSTRAINTS PURGE;

DROP SEQUENCE PER_COMPANY_TYPE_SEQ;
DROP TABLE PER_COMPANY_TYPE CASCADE CONSTRAINTS PURGE;

DROP SEQUENCE PER_CIVIL_STATUS_SEQ;
DROP TABLE PER_CIVIL_STATUS CASCADE CONSTRAINTS PURGE;

DROP SEQUENCE PER_PERSON_STATUS_SEQ;
DROP TABLE PER_PERSON_STATUS CASCADE CONSTRAINTS PURGE;

DROP SEQUENCE PER_LANGUAGE_SEQ;
DROP TABLE PER_LANGUAGE CASCADE CONSTRAINTS PURGE;

DROP SEQUENCE PER_ID_TYPE_SEQ;
DROP TABLE PER_ID_TYPE CASCADE CONSTRAINTS PURGE;

DROP SEQUENCE PER_CONTACT_TYPE_SEQ;
DROP TABLE PER_CONTACT_TYPE CASCADE CONSTRAINTS PURGE;

DROP SEQUENCE PER_RELATION_TYPE_SEQ;
DROP TABLE PER_RELATION_TYPE CASCADE CONSTRAINTS PURGE;

DROP SEQUENCE PER_COMPANY_PERSON_TYPE_SEQ;
DROP TABLE PER_COMPANY_PERSON_TYPE CASCADE CONSTRAINTS PURGE;