-- PER_CARD_TYPE
INSERT INTO ITACA.PER_CARD_TYPE
(CARD_TYPE_ID, LITERAL)
VALUES(1, 'DEBITO');
INSERT INTO ITACA.PER_CARD_TYPE
(CARD_TYPE_ID, LITERAL)
VALUES(2, 'CREDITO');
-- PER_CARD_TYPE
INSERT INTO ITACA.PER_BANK
(BANK_ID, BANK_COD, BANK_NAME, CBIC, DRAFT_BANK_PORTAL)
VALUES(1,'Ban01','Banesco','S','001');
-- PER_TYPE_ACCOUNT
INSERT INTO ITACA.PER_TYPE_ACCOUNT
(TYPE_ACCOUNT_ID,VALUE_TYPE_ACCOUNT)
values (1,'CORRIENTE');
INSERT INTO ITACA.PER_TYPE_ACCOUNT
(TYPE_ACCOUNT_ID,VALUE_TYPE_ACCOUNT)
values (2,'AHORRO')
-- PER_CLASIFICATION_ACCOUNT
INSERT INTO ITACA.PER_CLASIFICATION_ACCOUNT
(CLASIFICATION_ACCOUNT_ID,VALUE_CLASIFICATION_ACCOUNT)
VALUES (1,'NORMALIZADA');

COMMIT;