
-- contact
INSERT INTO "ITACA"."PER_CONTACT" (PER_CONTACT_ID, PERSON_DETAIL_ID, CONTACT_TYPE_ID, ADDRESS_ID, VALUE_CONTACT) VALUES ('1', '1', '2', '445566', '1');
INSERT INTO "ITACA"."PER_CONTACT" (PER_CONTACT_ID, PERSON_DETAIL_ID, CONTACT_TYPE_ID, ADDRESS_ID, VALUE_CONTACT) VALUES ('2', '2', '2', '445577', '1');
INSERT INTO "ITACA"."PER_CONTACT" (PER_CONTACT_ID, PERSON_DETAIL_ID, CONTACT_TYPE_ID, ADDRESS_ID, VALUE_CONTACT) VALUES ('3', '3', '2', '445588', '1');
INSERT INTO "ITACA"."PER_CONTACT" (PER_CONTACT_ID, PERSON_DETAIL_ID, CONTACT_TYPE_ID, ADDRESS_ID, VALUE_CONTACT) VALUES ('4', '4', '2', '445599', '1');

commit;

