----------------- PEOPLE table space  -----------------
--CREATE TABLESPACE "LOAD" DATAFILE '/u02/oradata/sigma01/load.dbf' SIZE 1024M
CREATE TABLESPACE "LOAD" DATAFILE 'C:\\Desarrollo\\CSI\\OracleDataFile\\SIGMA01\\load.dbf' SIZE 1024M
AUTOEXTEND ON NEXT 100M MAXSIZE 32767M
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;
----------------- PEOPLE table space end por si  -----------------

