----------------- LOGIN table space  -----------------
CREATE TABLESPACE "LOGIN" DATAFILE '/u02/oradata/sigma01/login.dbf' SIZE 1024M
AUTOEXTEND ON NEXT 100M MAXSIZE 32767M
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;
----------------- LOGIN table space end  -----------------