INSERT INTO "DIR_COUNTRY" (COUNTRY_ID, ISO_CODE, NAME) VALUES ('1', 'ESP', 'Spain');
INSERT INTO "DIR_COUNTRY" (COUNTRY_ID, ISO_CODE, NAME) VALUES ('2', 'COL', 'Colombia');
INSERT INTO "DIR_COUNTRY" (COUNTRY_ID, ISO_CODE, NAME) VALUES ('3', 'CHL', 'Chile');
INSERT INTO "DIR_COUNTRY" (COUNTRY_ID, ISO_CODE, NAME) VALUES ('4', 'UK', 'United Kingdom');

commit;