CREATE TABLE "LD_PRELOAD_FIELD_DEFINITION"
(	"PRELOAD_FIELD_DEFINITION_ID" NUMBER NOT NULL ENABLE,
   "PRELOAD_ROW_TYPE_ID" NUMBER,
   "COLUMN_NO" NUMBER NOT NULL ENABLE,
   "NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
   "DESCRIPTION" VARCHAR2(255 BYTE),
   "PRELOAD_FIELD_TYPE_ID" NUMBER,
   "REGEX" VARCHAR2(100 BYTE),
   "REQUIRED" VARCHAR2(1 BYTE),
   "REL_TYPE" NUMBER DEFAULT 0,
   "REL_FIELD_DEFINITION_ID" NUMBER,
   "REL_DB_TABLE_NAME" VARCHAR2(50 BYTE),
   "REL_DB_FIELD_NAME" VARCHAR2(50 BYTE),
   "ERROR_SEVERITY" NUMBER,
  CONSTRAINT "LD_PRELOAD_FIELD_DEFINITIO_PK" PRIMARY KEY ("PRELOAD_FIELD_DEFINITION_ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "DIR"  ENABLE,
  CONSTRAINT "FK_PRELOADROWTYPEID" FOREIGN KEY ("PRELOAD_ROW_TYPE_ID")
  REFERENCES "LD_PRELOAD_ROW_TYPE" ("PRELOAD_ROW_TYPE_ID") ENABLE,
  CONSTRAINT "FK_PRELOADFIELDTYPEID" FOREIGN KEY ("PRELOAD_FIELD_TYPE_ID")
  REFERENCES "LD_PRELOAD_FIELD_TYPE" ("PRELOAD_FIELD_TYPE_ID") ENABLE
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DIR" ;

COMMENT ON COLUMN "LD_PRELOAD_FIELD_DEFINITION"."PRELOAD_FIELD_DEFINITION_ID" IS 'Primary key';
COMMENT ON COLUMN "LD_PRELOAD_FIELD_DEFINITION"."PRELOAD_ROW_TYPE_ID" IS 'Referencing load file';
COMMENT ON COLUMN "LD_PRELOAD_FIELD_DEFINITION"."COLUMN_NO" IS 'Column number in the load file';
COMMENT ON COLUMN "LD_PRELOAD_FIELD_DEFINITION"."NAME" IS 'Name of this item';
COMMENT ON COLUMN "LD_PRELOAD_FIELD_DEFINITION"."DESCRIPTION" IS 'Description of this item';
COMMENT ON COLUMN "LD_PRELOAD_FIELD_DEFINITION"."PRELOAD_FIELD_TYPE_ID" IS 'Referencing field type';
COMMENT ON COLUMN "LD_PRELOAD_FIELD_DEFINITION"."REGEX" IS 'Validation regular expression';
COMMENT ON COLUMN "LD_PRELOAD_FIELD_DEFINITION"."REQUIRED" IS 'Indicates if this field is required';
COMMENT ON COLUMN "LD_PRELOAD_FIELD_DEFINITION"."REL_TYPE" IS '0 No mapping
1 Load schema
2 Database table
3 Search in both';
COMMENT ON COLUMN "LD_PRELOAD_FIELD_DEFINITION"."REL_FIELD_DEFINITION_ID" IS 'Referencing another field definition
in the same schema of the load';
COMMENT ON COLUMN "LD_PRELOAD_FIELD_DEFINITION"."REL_DB_TABLE_NAME" IS 'References a table name outside the
load schema within the database
schema';
COMMENT ON COLUMN "LD_PRELOAD_FIELD_DEFINITION"."REL_DB_FIELD_NAME" IS 'References a field name outside the
load schema within the database
schema';
COMMENT ON COLUMN "LD_PRELOAD_FIELD_DEFINITION"."ERROR_SEVERITY" IS '1 Low
2 Medium
3 High';
