CREATE TABLE "LD_PRELOAD_FILE"
(	"PRELOAD_FILE_ID" NUMBER NOT NULL ENABLE,
   "PRELOAD_DEFINITION_ID" NUMBER,
   "NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
   "DESCRIPTION" VARCHAR2(255 BYTE),
   "FILENAME_FORMAT_REGEX" VARCHAR2(100 BYTE),
  CONSTRAINT "LD_PRELOAD_FILE_PK" PRIMARY KEY ("PRELOAD_FILE_ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "DIR"  ENABLE,
  CONSTRAINT "FK_PRELOADDEFINITIONID" FOREIGN KEY ("PRELOAD_DEFINITION_ID")
  REFERENCES "LD_PRELOAD_DEFINITION" ("PRELOAD_DEFINITION_ID") ENABLE
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DIR" ;

COMMENT ON COLUMN "LD_PRELOAD_FILE"."PRELOAD_FILE_ID" IS 'Primary key';
COMMENT ON COLUMN "LD_PRELOAD_FILE"."PRELOAD_DEFINITION_ID" IS 'Referencing preload definition.';
COMMENT ON COLUMN "LD_PRELOAD_FILE"."NAME" IS 'Name of this item';
COMMENT ON COLUMN "LD_PRELOAD_FILE"."DESCRIPTION" IS 'Description of this item';
COMMENT ON COLUMN "LD_PRELOAD_FILE"."FILENAME_FORMAT_REGEX" IS 'Regular expression for the
filename format';