CREATE TABLE LD_PRELOAD_ROW_TYPE
(
  PRELOAD_ROW_TYPE_ID   NUMBER                  NOT NULL,
  PRELOAD_FILE_ID       NUMBER,
  NAME                  VARCHAR2(50 BYTE)       NOT NULL,
  DESCRIPTION           VARCHAR2(255 BYTE),
  IDENTIFIER_COLUMN_NO  NUMBER                  DEFAULT 1,
  IDENTIFIER_VALUE      VARCHAR2(255 BYTE)
)
TABLESPACE LOAD LOGGING;


CREATE SEQUENCE SEQ_PRELOAD_ROW_TYPE_ID MINVALUE 1 MAXVALUE 99999999999  START WITH 1 INCREMENT BY 1 CACHE 20;


COMMENT ON COLUMN LD_PRELOAD_ROW_TYPE.PRELOAD_ROW_TYPE_ID IS 'Primary key';

COMMENT ON COLUMN LD_PRELOAD_ROW_TYPE.PRELOAD_FILE_ID IS 'Referencing preload file';

COMMENT ON COLUMN LD_PRELOAD_ROW_TYPE.NAME IS 'Name of this item';

COMMENT ON COLUMN LD_PRELOAD_ROW_TYPE.DESCRIPTION IS 'Description of this item';

COMMENT ON COLUMN LD_PRELOAD_ROW_TYPE.IDENTIFIER_COLUMN_NO IS 'This row type identifier column number in
the file';

COMMENT ON COLUMN LD_PRELOAD_ROW_TYPE.IDENTIFIER_VALUE IS 'This row type identifier value';


CREATE UNIQUE INDEX LD_PRELOAD_ROW_TYPE_PK ON LD_PRELOAD_ROW_TYPE(PRELOAD_ROW_TYPE_ID);

ALTER TABLE LD_PRELOAD_ROW_TYPE ADD (CONSTRAINT LD_PRELOAD_ROW_TYPE_PK PRIMARY KEY (PRELOAD_ROW_TYPE_ID) USING INDEX LD_PRELOAD_ROW_TYPE_PK  ENABLE VALIDATE);

ALTER TABLE LD_PRELOAD_ROW_TYPE ADD (CONSTRAINT FK_PRELOADFILEID FOREIGN KEY (PRELOAD_FILE_ID) REFERENCES LD_PRELOAD_FILE (PRELOAD_FILE_ID) ENABLE VALIDATE);