-- Deploy itaca-load:CreateLdLoadRowOperation to oracle
-- XXX Add DDLs here.
create table LD_LOAD_ROW_OPERATION
(
	LOAD_ROW_OPERATION_ID NUMBER not null
		primary key,
	LOAD_OPERATION_TYPE_ID NUMBER,
	PRELOAD_ROW_TYPE_ID NUMBER,
	LOAD_DEFINITIVE_TABLE_ID NUMBER,
	KEY_COLUMN_NO NUMBER,
	OPERATION_ORDER NUMBER
)
TABLESPACE LOAD LOGGING
/

comment on table LD_LOAD_ROW_OPERATION is 'load_row_operation'
/

comment on column LD_LOAD_ROW_OPERATION.LOAD_ROW_OPERATION_ID is 'Primary key.'
/

comment on column LD_LOAD_ROW_OPERATION.LOAD_OPERATION_TYPE_ID is 'Associated operation type.'
/

comment on column LD_LOAD_ROW_OPERATION.PRELOAD_ROW_TYPE_ID is 'Associated row type.'
/

comment on column LD_LOAD_ROW_OPERATION.LOAD_DEFINITIVE_TABLE_ID is 'Associated definitive table.'
/

comment on column LD_LOAD_ROW_OPERATION.KEY_COLUMN_NO is 'Key column in the preload
data.'
/

comment on column LD_LOAD_ROW_OPERATION.OPERATION_ORDER is 'Numerical order of operation.'
/

ALTER TABLE LD_LOAD_ROW_OPERATION ADD CONSTRAINT LD_LOAD_ROW_OPERATION_FK1 FOREIGN KEY ( LOAD_OPERATION_TYPE_ID ) REFERENCES LD_LOAD_OPERATION_TYPE ( LOAD_OPERATION_TYPE_ID ) NOT DEFERRABLE

/

ALTER TABLE LD_LOAD_ROW_OPERATION ADD CONSTRAINT LD_LOAD_ROW_OPERATION_FK2 FOREIGN KEY ( PRELOAD_ROW_TYPE_ID ) REFERENCES LD_PRELOAD_FIELD_TYPE ( PRELOAD_FIELD_TYPE_ID ) NOT DEFERRABLE

/

ALTER TABLE LD_LOAD_ROW_OPERATION ADD CONSTRAINT LD_LOAD_ROW_OPERATION_FK3 FOREIGN KEY ( LOAD_DEFINITIVE_TABLE_ID ) REFERENCES LD_LOAD_DEFINITIVE_TABLE ( LOAD_DEFINITIVE_TABLE_ID ) NOT DEFERRABLE

/

CREATE SEQUENCE ld_load_row_operation_seq START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999 MINVALUE 1 NOCACHE

/
