-- Deploy itaca-load:CreateLdLoadAuditLog to oracle
-- XXX Add DDLs here.
create table LD_LOAD_AUDIT_LOG
(
	LOAD_AUDIT_LOG_ID NUMBER not null
		primary key,
	LOAD_PROCESS_ID NUMBER,
	LOAD_ROW_OPERATION_ID NUMBER,
	LOAD_OPERATION_TYPE_ID NUMBER,
	ATOMIC_OP_CODE NUMBER,
	PRELOAD_DATA_ID NUMBER,
	USER_ID NUMBER,
	OPERATION_TIMESTAMP DATE,
	DEFINITIVE_VALUES_BEFORE_JSON VARCHAR2(1000),
	DEFINITIVE_VALUES_AFTER_JSON VARCHAR2(1000),
	SQL_COMMAND_APPLIED VARCHAR2(1000)
)
TABLESPACE LOAD LOGGING
/

comment on table LD_LOAD_AUDIT_LOG is 'load_audit_log'
/

comment on column LD_LOAD_AUDIT_LOG.LOAD_AUDIT_LOG_ID is 'Primary key.'
/

comment on column LD_LOAD_AUDIT_LOG.LOAD_PROCESS_ID is 'Associated load process.'
/

comment on column LD_LOAD_AUDIT_LOG.LOAD_ROW_OPERATION_ID is 'Associated row operation.'
/

comment on column LD_LOAD_AUDIT_LOG.LOAD_OPERATION_TYPE_ID is 'Associated operation type.'
/

comment on column LD_LOAD_AUDIT_LOG.ATOMIC_OP_CODE is 'The associated atomic
operation.'
/

comment on column LD_LOAD_AUDIT_LOG.PRELOAD_DATA_ID is 'The row this error is associated.'
/

comment on column LD_LOAD_AUDIT_LOG.USER_ID is 'User who initiated the load.'
/

comment on column LD_LOAD_AUDIT_LOG.OPERATION_TIMESTAMP is 'Time of operation.'
/

comment on column LD_LOAD_AUDIT_LOG.DEFINITIVE_VALUES_BEFORE_JSON is 'Values before change'
/

comment on column LD_LOAD_AUDIT_LOG.DEFINITIVE_VALUES_AFTER_JSON is 'Values after change'
/

comment on column LD_LOAD_AUDIT_LOG.SQL_COMMAND_APPLIED is 'The sql command that was
applied.'
/
ALTER TABLE LD_LOAD_AUDIT_LOG ADD CONSTRAINT LD_LOAD_AUDIT_LOG_FK1 FOREIGN KEY ( LOAD_PROCESS_ID ) REFERENCES LD_LOAD_PROCESS ( LOAD_PROCESS_ID ) NOT DEFERRABLE

/
ALTER TABLE LD_LOAD_AUDIT_LOG ADD CONSTRAINT LD_LOAD_AUDIT_LOG_FK2 FOREIGN KEY ( LOAD_ROW_OPERATION_ID ) REFERENCES LD_LOAD_ROW_OPERATION ( LOAD_ROW_OPERATION_ID ) NOT DEFERRABLE

/
ALTER TABLE LD_LOAD_AUDIT_LOG ADD CONSTRAINT LD_LOAD_AUDIT_LOG_FK3 FOREIGN KEY ( LOAD_OPERATION_TYPE_ID ) REFERENCES LD_LOAD_OPERATION_TYPE ( LOAD_OPERATION_TYPE_ID ) NOT DEFERRABLE

/
ALTER TABLE LD_LOAD_AUDIT_LOG ADD CONSTRAINT LD_LOAD_AUDIT_LOG_FK4 FOREIGN KEY ( ATOMIC_OP_CODE ) REFERENCES LD_LOAD_ATOMIC_OPERATION ( LOAD_ATOMIC_OPERATION_ID ) NOT DEFERRABLE

/
ALTER TABLE LD_LOAD_AUDIT_LOG ADD CONSTRAINT LD_LOAD_AUDIT_LOG_FK5 FOREIGN KEY ( PRELOAD_DATA_ID ) REFERENCES LD_PRELOAD_DATA ( PRELOAD_DATA_ID ) NOT DEFERRABLE

/

CREATE SEQUENCE ld_load_audit_log_seq START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999 MINVALUE 1 NOCACHE

/

