-- Deploy itaca-load:CreateLdLoadDefinitiveMap to oracle
-- XXX Add DDLs here.
create table LD_LOAD_DEFINITIVE_MAP
(
	LOAD_DEFINITIVE_MAP_ID NUMBER not null
		primary key,
	LOAD_ROW_OPERATION_ID NUMBER,
	ATOMIC_OP_CODE NUMBER,
	COLUMN_NO NUMBER,
	LOAD_DEFINITIVE_FIELD_ID NUMBER
)
TABLESPACE LOAD LOGGING
/

comment on table LD_LOAD_DEFINITIVE_MAP is 'load_definitive_map'
/

comment on column LD_LOAD_DEFINITIVE_MAP.LOAD_DEFINITIVE_MAP_ID is 'Primary key.'
/

comment on column LD_LOAD_DEFINITIVE_MAP.LOAD_ROW_OPERATION_ID is 'Associated row operation.'
/

comment on column LD_LOAD_DEFINITIVE_MAP.ATOMIC_OP_CODE is 'The associated atomic
operation.'
/

comment on column LD_LOAD_DEFINITIVE_MAP.COLUMN_NO is 'Column no in the preload data.'
/

comment on column LD_LOAD_DEFINITIVE_MAP.LOAD_DEFINITIVE_FIELD_ID is 'References the definitive field.'
/
ALTER TABLE LD_LOAD_DEFINITIVE_MAP ADD CONSTRAINT LD_LOAD_DEFINITIVE_MAP_FK1 FOREIGN KEY ( LOAD_ROW_OPERATION_ID ) REFERENCES LD_LOAD_ROW_OPERATION ( LOAD_ROW_OPERATION_ID ) NOT DEFERRABLE

/
ALTER TABLE LD_LOAD_DEFINITIVE_MAP ADD CONSTRAINT LD_LOAD_DEFINITIVE_MAP_FK2 FOREIGN KEY ( ATOMIC_OP_CODE ) REFERENCES LD_LOAD_ATOMIC_OPERATION ( LOAD_ATOMIC_OPERATION_ID ) NOT DEFERRABLE

/
ALTER TABLE LD_LOAD_DEFINITIVE_MAP ADD CONSTRAINT LD_LOAD_DEFINITIVE_MAP_FK3 FOREIGN KEY ( LOAD_DEFINITIVE_FIELD_ID ) REFERENCES LD_LOAD_DEFINITIVE_FIELD ( LOAD_DEFINITIVE_FIELD_ID ) NOT DEFERRABLE

/

CREATE SEQUENCE ld_load_definitive_map_seq START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999 MINVALUE 1 NOCACHE

/
