CREATE TABLE "LD_LOAD_PROCESS"
(	"LOAD_PROCESS_ID" NUMBER NOT NULL ENABLE,
   "USER_ID" NUMBER,
   "CREATED_TIMESTAMP" DATE,
   "PRELOAD_DEFINITION_ID" NUMBER,
  CONSTRAINT "LD_LOAD_PROCESS_PK" PRIMARY KEY ("LOAD_PROCESS_ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "DIR"  ENABLE
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DIR" ;

COMMENT ON COLUMN "LD_LOAD_PROCESS"."LOAD_PROCESS_ID" IS 'Primary key';
COMMENT ON COLUMN "LD_LOAD_PROCESS"."USER_ID" IS 'The user who initiated the upload';
COMMENT ON COLUMN "LD_LOAD_PROCESS"."CREATED_TIMESTAMP" IS 'Date and time the load was created';
COMMENT ON COLUMN "LD_LOAD_PROCESS"."PRELOAD_DEFINITION_ID" IS 'Associated preload definition';
