CREATE TABLE LD_PRELOAD_FIELD_DEFINITION
(
  PRELOAD_FIELD_DEFINITION_ID  NUMBER           NOT NULL,
  PRELOAD_ROW_TYPE_ID          NUMBER,
  COLUMN_NO                    NUMBER           NOT NULL,
  LENGTH                       NUMBER,
  NAME                         VARCHAR2(50 BYTE) NOT NULL,
  DESCRIPTION                  VARCHAR2(255 BYTE),
  PRELOAD_FIELD_TYPE_ID        NUMBER,
  REGEX                        VARCHAR2(100 BYTE),
  REQUIRED                     VARCHAR2(1 BYTE),
  REL_TYPE                     NUMBER           DEFAULT 0,
  REL_FIELD_DEFINITION_ID      NUMBER,
  REL_DB_TABLE_NAME            VARCHAR2(50 BYTE),
  REL_DB_FIELD_NAME            VARCHAR2(50 BYTE),
  ERROR_SEVERITY               NUMBER
)
TABLESPACE LOAD LOGGING;


CREATE SEQUENCE SEQ_PRE_FIEL_DEF_ID   MINVALUE 1 MAXVALUE 99999999999  START WITH 1 INCREMENT BY 1 CACHE 20;

COMMENT ON COLUMN LD_PRELOAD_FIELD_DEFINITION.PRELOAD_FIELD_DEFINITION_ID IS 'Primary key';

COMMENT ON COLUMN LD_PRELOAD_FIELD_DEFINITION.PRELOAD_ROW_TYPE_ID IS 'Referencing load file';

COMMENT ON COLUMN LD_PRELOAD_FIELD_DEFINITION.COLUMN_NO IS 'Column number in the load file';

COMMENT ON COLUMN LD_PRELOAD_FIELD_DEFINITION.LENGTH IS 'Use for file “TXT” format';

COMMENT ON COLUMN LD_PRELOAD_FIELD_DEFINITION.NAME IS 'Name of this item';

COMMENT ON COLUMN LD_PRELOAD_FIELD_DEFINITION.DESCRIPTION IS 'Description of this item';

COMMENT ON COLUMN LD_PRELOAD_FIELD_DEFINITION.PRELOAD_FIELD_TYPE_ID IS 'Referencing field type';

COMMENT ON COLUMN LD_PRELOAD_FIELD_DEFINITION.REGEX IS 'Validation regular expression';

COMMENT ON COLUMN LD_PRELOAD_FIELD_DEFINITION.REQUIRED IS 'Indicates if this field is required';

COMMENT ON COLUMN LD_PRELOAD_FIELD_DEFINITION.REL_TYPE IS '0 No mapping
1 Load schema
2 Database table
3 Search in both';

COMMENT ON COLUMN LD_PRELOAD_FIELD_DEFINITION.REL_FIELD_DEFINITION_ID IS 'Referencing another field definition
in the same schema of the load';

COMMENT ON COLUMN LD_PRELOAD_FIELD_DEFINITION.REL_DB_TABLE_NAME IS 'References a table name outside the
load schema within the database
schema';

COMMENT ON COLUMN LD_PRELOAD_FIELD_DEFINITION.REL_DB_FIELD_NAME IS 'References a field name outside the
load schema within the database
schema';

COMMENT ON COLUMN LD_PRELOAD_FIELD_DEFINITION.ERROR_SEVERITY IS '1 Low
2 Medium
3 High';


CREATE UNIQUE INDEX LD_PRELOAD_FIELD_DEFINITIO_PK ON LD_PRELOAD_FIELD_DEFINITION(PRELOAD_FIELD_DEFINITION_ID);

ALTER TABLE LD_PRELOAD_FIELD_DEFINITION ADD (CONSTRAINT LD_PRELOAD_FIELD_DEFINITIO_PK PRIMARY KEY (PRELOAD_FIELD_DEFINITION_ID)  USING INDEX LD_PRELOAD_FIELD_DEFINITIO_PK ENABLE VALIDATE);

ALTER TABLE LD_PRELOAD_FIELD_DEFINITION ADD ( CONSTRAINT FK_PRELOADROWTYPEID FOREIGN KEY (PRELOAD_ROW_TYPE_ID) REFERENCES LD_PRELOAD_ROW_TYPE (PRELOAD_ROW_TYPE_ID) ENABLE VALIDATE);

ALTER TABLE LD_PRELOAD_FIELD_DEFINITION ADD (CONSTRAINT FK_PRELOADFIELDTYPEID  FOREIGN KEY (PRELOAD_FIELD_TYPE_ID) REFERENCES LD_PRELOAD_FIELD_TYPE (PRELOAD_FIELD_TYPE_ID) ENABLE VALIDATE);

ALTER TABLE LD_PRELOAD_FIELD_DEFINITION ADD (CONSTRAINT FK_columnno FOREIGN KEY (COLUMN_NO) REFERENCES LD_PRELOAD_ROW_TYPE (PRELOAD_ROW_TYPE_ID) ENABLE VALIDATE);