CREATE TABLE LD_PRELOAD_DEFINITION
(
  PRELOAD_DEFINITION_ID      NUMBER             NOT NULL,
  NAME                       VARCHAR2(50 BYTE),
  DESCRIPTION                VARCHAR2(255 BYTE),
  MAX_PRELOAD_LOW_ERRORS     NUMBER,
  MAX_PRELOAD_MEDIUM_ERRORS  NUMBER,
  MAX_PRELOAD_HIGH_ERRORS    NUMBER,
  LOAD_IF_PRELOAD_OK         VARCHAR2(20 BYTE),
  AUTO_LOAD_DIRECTORY        VARCHAR2(1024 BYTE),
  AUTO_CRON_SCHEDULING       VARCHAR2(20 BYTE),
  AUTO_ENABLED               BLOB
)
TABLESPACE LOAD LOGGING;

CREATE SEQUENCE SEQ_PRELOAD_DEFINITION_ID   MINVALUE 1 MAXVALUE 99999999999  START WITH 1 INCREMENT BY 1 CACHE 20;

COMMENT ON COLUMN LD_PRELOAD_DEFINITION.PRELOAD_DEFINITION_ID IS 'Primary key';

COMMENT ON COLUMN LD_PRELOAD_DEFINITION.NAME IS 'Name of this item';

COMMENT ON COLUMN LD_PRELOAD_DEFINITION.DESCRIPTION IS 'Description of this item';

COMMENT ON COLUMN LD_PRELOAD_DEFINITION.MAX_PRELOAD_LOW_ERRORS IS 'Maximum allowed preload low errors. The
process will stop if this number is exceeded';

COMMENT ON COLUMN LD_PRELOAD_DEFINITION.MAX_PRELOAD_MEDIUM_ERRORS IS 'Maximum allowed preload medium errors.
The process will stop if this number is
exceeded';

COMMENT ON COLUMN LD_PRELOAD_DEFINITION.MAX_PRELOAD_HIGH_ERRORS IS 'Maximum allowed preload high errors. The
process will stop if this number is exceeded';

COMMENT ON COLUMN LD_PRELOAD_DEFINITION.LOAD_IF_PRELOAD_OK IS 'Indicates to the application whether to
automatically start the load if the preload
completed successfully with no medium or
high errors';

COMMENT ON COLUMN LD_PRELOAD_DEFINITION.AUTO_LOAD_DIRECTORY IS 'Directory location. This can either be a directory of the local server, network folder
or FTP location.';

COMMENT ON COLUMN LD_PRELOAD_DEFINITION.AUTO_CRON_SCHEDULING IS 'Time in which the preload will automatically
run. Standard cron format
(https://en.wikipedia.org/wiki/Cron)';

COMMENT ON COLUMN LD_PRELOAD_DEFINITION.AUTO_ENABLED IS 'True will indicate that this job is enabled';


CREATE UNIQUE INDEX LD_PRELOAD_DEFINITION_PK ON LD_PRELOAD_DEFINITION(PRELOAD_DEFINITION_ID);

ALTER TABLE LD_PRELOAD_DEFINITION ADD (CONSTRAINT LD_PRELOAD_DEFINITION_PK PRIMARY KEY(PRELOAD_DEFINITION_ID) USING INDEX LD_PRELOAD_DEFINITION_PK  ENABLE VALIDATE);