CREATE TABLE "LD_ERROR_FIELD"
(	"ERR_FIELDS_ID" NUMBER NOT NULL ENABLE,
   "PRELOAD_DATA_ID" NUMBER,
   "PRELOAD_FIELD_DEFINITION_ID" VARCHAR2(20 BYTE),
   "VALIDATION_ERR_MSG" VARCHAR2(200 BYTE),
  CONSTRAINT "LD_ERROR_FIELD_PK" PRIMARY KEY ("ERR_FIELDS_ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "DIR"  ENABLE,
  CONSTRAINT "FK_PRELOADDATAID" FOREIGN KEY ("PRELOAD_DATA_ID")
  REFERENCES "LD_PRELOAD_DATA" ("PRELOAD_DATA_ID") ENABLE
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DIR" ;

COMMENT ON COLUMN "LD_ERROR_FIELD"."ERR_FIELDS_ID" IS 'Primary key';
COMMENT ON COLUMN "LD_ERROR_FIELD"."PRELOAD_DATA_ID" IS 'The row this error is associated';
COMMENT ON COLUMN "LD_ERROR_FIELD"."PRELOAD_FIELD_DEFINITION_ID" IS 'Associate preload definition field';
COMMENT ON COLUMN "LD_ERROR_FIELD"."VALIDATION_ERR_MSG" IS 'Contains a description the detected
validation error for this field';