CREATE TABLE "LD_PRELOAD_FIELD_TYPE"
(	"PRELOAD_FIELD_TYPE_ID" NUMBER NOT NULL ENABLE,
   "NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
   "DESCRIPTION" VARCHAR2(255 BYTE),
   "MIN_LENGTH" NUMBER,
   "MAX_LENGTH" NUMBER,
   "REGEX" VARCHAR2(100 BYTE),
  CONSTRAINT "LD_PRELOAD_FIELD_TYPE_PK" PRIMARY KEY ("PRELOAD_FIELD_TYPE_ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "DIR"  ENABLE
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DIR" ;

COMMENT ON COLUMN "LD_PRELOAD_FIELD_TYPE"."PRELOAD_FIELD_TYPE_ID" IS 'Primary key';
COMMENT ON COLUMN "LD_PRELOAD_FIELD_TYPE"."NAME" IS 'Name of this item';
COMMENT ON COLUMN "LD_PRELOAD_FIELD_TYPE"."DESCRIPTION" IS 'Description of this item';
COMMENT ON COLUMN "LD_PRELOAD_FIELD_TYPE"."MIN_LENGTH" IS 'Minimum length of the field';
COMMENT ON COLUMN "LD_PRELOAD_FIELD_TYPE"."MAX_LENGTH" IS 'Maximum length of the field';
COMMENT ON COLUMN "LD_PRELOAD_FIELD_TYPE"."REGEX" IS 'Regular expression the value must
follow.';