CREATE TABLE LD_PRELOAD_DATA
(
  PRELOAD_DATA_ID      NUMBER                   NOT NULL,
  LOAD_FILE_ID         NUMBER,
  LOADED_SUCCESSFULLY  VARCHAR2(1 BYTE),
  created_timestamp    DATE,
  ROW_TYPE             NUMBER,
  LINE_NUMBER          NUMBER,
  DATA_COL1            VARCHAR2(1024 BYTE),
  DATA_COL2            VARCHAR2(1024 BYTE),
  DATA_COL3            VARCHAR2(1024 BYTE)
)
TABLESPACE LOAD LOGGING;

CREATE SEQUENCE SEQ_PRELOAD_DATA_ID   MINVALUE 1 MAXVALUE 99999999999  START WITH 1 INCREMENT BY 1 CACHE 20;

COMMENT ON COLUMN LD_PRELOAD_DATA.PRELOAD_DATA_ID IS 'Primary key';

COMMENT ON COLUMN LD_PRELOAD_DATA.LOAD_FILE_ID IS 'The upload file id of which the current row is
associated';

COMMENT ON COLUMN LD_PRELOAD_DATA.LOADED_SUCCESSFULLY IS 'True if this row was successfully loaded into
the business tables';

COMMENT ON COLUMN LD_PRELOAD_DATA.ROW_TYPE IS 'Row type used to parse this row from the file';

COMMENT ON COLUMN LD_PRELOAD_DATA.LINE_NUMBER IS 'The associated line number within the file';

COMMENT ON COLUMN LD_PRELOAD_DATA.DATA_COL1 IS 'Data source column 1';

COMMENT ON COLUMN LD_PRELOAD_DATA.DATA_COL2 IS 'Data source column 2';

COMMENT ON COLUMN LD_PRELOAD_DATA.DATA_COL3 IS 'Data source column 3';


CREATE UNIQUE INDEX LD_PRELOAD_DATA_PK ON LD_PRELOAD_DATA (PRELOAD_DATA_ID);

ALTER TABLE LD_PRELOAD_DATA ADD (CONSTRAINT LD_PRELOAD_DATA_PK PRIMARY KEY (PRELOAD_DATA_ID) USING INDEX LD_PRELOAD_DATA_PK ENABLE VALIDATE);