CREATE TABLE LD_ERROR_FIELD
(
  ERR_FIELDS_ID                NUMBER           NOT NULL,
  PRELOAD_DATA_ID              NUMBER,
  PRELOAD_FIELD_DEFINITION_ID  NUMBER,
  VALIDATION_ERR_MSG           VARCHAR2(200 BYTE)
)
TABLESPACE LOAD LOGGING;


CREATE SEQUENCE SEQ_Pre_Def_Id   MINVALUE 1 MAXVALUE 99999999999  START WITH 1 INCREMENT BY 1 CACHE 20;

COMMENT ON COLUMN LD_ERROR_FIELD.ERR_FIELDS_ID IS 'Primary key';

COMMENT ON COLUMN LD_ERROR_FIELD.PRELOAD_DATA_ID IS 'The row this error is associated';

COMMENT ON COLUMN LD_ERROR_FIELD.PRELOAD_FIELD_DEFINITION_ID IS 'Associate preload definition field';

COMMENT ON COLUMN LD_ERROR_FIELD.VALIDATION_ERR_MSG IS 'Contains a description the detected
validation error for this field';


CREATE UNIQUE INDEX LD_ERROR_FIELD_PK ON LD_ERROR_FIELD (ERR_FIELDS_ID);

ALTER TABLE LD_ERROR_FIELD ADD (CONSTRAINT LD_ERROR_FIELD_PK PRIMARY KEY (ERR_FIELDS_ID) USING INDEX LD_ERROR_FIELD_PK ENABLE VALIDATE);

ALTER TABLE LD_ERROR_FIELD ADD (CONSTRAINT FK_PRELOADDATAID  FOREIGN KEY (PRELOAD_DATA_ID) REFERENCES LD_PRELOAD_DATA (PRELOAD_DATA_ID) ENABLE VALIDATE);

ALTER TABLE LD_ERROR_FIELD ADD (CONSTRAINT FK_PRELOADFIELDDEFINITIONID  FOREIGN KEY (PRELOAD_FIELD_DEFINITION_ID) REFERENCES ld_preload_field_definition (preload_field_definition_id) ENABLE VALIDATE);