CREATE TABLE LD_PRELOAD_FIELD_TYPE
(
  PRELOAD_FIELD_TYPE_ID  NUMBER                 NOT NULL,
  NAME                   VARCHAR2(50 BYTE)      NOT NULL,
  DESCRIPTION            VARCHAR2(255 BYTE),
  MIN_LENGTH             NUMBER,
  MAX_LENGTH             NUMBER,
  REGEX                  VARCHAR2(100 BYTE)
)
TABLESPACE LOAD LOGGING;


CREATE SEQUENCE SEQ_PRELOAD_FIELD_TYPE_ID   MINVALUE 1 MAXVALUE 99999999999  START WITH 1 INCREMENT BY 1 CACHE 20;


COMMENT ON COLUMN LD_PRELOAD_FIELD_TYPE.PRELOAD_FIELD_TYPE_ID IS 'Primary key';

COMMENT ON COLUMN LD_PRELOAD_FIELD_TYPE.NAME IS 'Name of this item';

COMMENT ON COLUMN LD_PRELOAD_FIELD_TYPE.DESCRIPTION IS 'Description of this item';

COMMENT ON COLUMN LD_PRELOAD_FIELD_TYPE.MIN_LENGTH IS 'Minimum length of the field';

COMMENT ON COLUMN LD_PRELOAD_FIELD_TYPE.MAX_LENGTH IS 'Maximum length of the field';

COMMENT ON COLUMN LD_PRELOAD_FIELD_TYPE.REGEX IS 'Regular expression the value must
follow.';


CREATE UNIQUE INDEX LD_PRELOAD_FIELD_TYPE_PK ON LD_PRELOAD_FIELD_TYPE (PRELOAD_FIELD_TYPE_ID);

ALTER TABLE LD_PRELOAD_FIELD_TYPE ADD (CONSTRAINT LD_PRELOAD_FIELD_TYPE_PK PRIMARY KEY(PRELOAD_FIELD_TYPE_ID) USING INDEX LD_PRELOAD_FIELD_TYPE_PK ENABLE VALIDATE);