--------------------------------------------------------
--  Sequence for Table CONTACT
--------------------------------------------------------

CREATE SEQUENCE SEQ_CONTACT START WITH 1 MAXVALUE 9999999999 MINVALUE 1 INCREMENT BY 1 NOCYCLE NOCACHE NOORDER;
--------------------------------------------------------
--  DDL for Table CONTACT
--------------------------------------------------------
CREATE TABLE PER_CONTACT
  (
    PER_CONTACT_ID  NUMBER (19) NOT NULL ,
    PERSON_DETAIL_ID   NUMBER (19) NOT NULL ,
    CONTACT_TYPE_ID NUMBER (19) NOT NULL ,
    ADDRESS_ID     NUMBER (19) ,
    VALUE_CONTACT   VARCHAR2 (100 CHAR) NOT NULL
  )    PCTFREE 10 PCTUSED 40 TABLESPACE PEOPLE LOGGING STORAGE
  (
    PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;

COMMENT ON TABLE PER_CONTACT
IS
  'CONTACTs de la persona' ;
  COMMENT ON COLUMN PER_CONTACT.PER_CONTACT_ID
IS
  'Identificador de CONTACTs' ;
  COMMENT ON COLUMN PER_CONTACT.PERSON_DETAIL_ID
IS
  'Identificador de persona asociada al CONTACT' ;
  COMMENT ON COLUMN PER_CONTACT.CONTACT_TYPE_ID
IS
  'Tipo de CONTACT (1-Telefono, 2-Fax, 3-E-mail)' ;
  COMMENT ON COLUMN PER_CONTACT.ADDRESS_ID
IS
  'Identificador de ADDRESS asociado al CONTACT' ;
  COMMENT ON COLUMN PER_CONTACT.VALUE_CONTACT
IS
  'Descripcion del CONTACT' ;
CREATE INDEX PER_CONTACT_ID1 ON PER_CONTACT
  (
    ADDRESS_ID ASC
  )  TABLESPACE PEOPLE PCTFREE 10 STORAGE
  (
    PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
CREATE INDEX PER_CONTACT_ID2 ON PER_CONTACT
  (
    PERSON_DETAIL_ID ASC
  )  TABLESPACE PEOPLE PCTFREE 10 STORAGE
  (
    PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
CREATE INDEX PER_CONTACT_ID3 ON PER_CONTACT
  (
    CONTACT_TYPE_ID ASC
  )  TABLESPACE PEOPLE PCTFREE 10 STORAGE
  (
    PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
CREATE INDEX PER_CONTACT_ID4 ON PER_CONTACT
  (
    PER_CONTACT_ID ASC
  )  TABLESPACE PEOPLE PCTFREE 10 STORAGE
  (
    PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;

-- *************************************** ADDRESS *************************************
CREATE
  TABLE DIR_ADDRESS
  (
    ADDRESS_ID NUMBER (19) NOT NULL ,
    FORMAT      VARCHAR2 (50 CHAR) NOT NULL
  )  PCTFREE 10 PCTUSED 40 TABLESPACE PEOPLE LOGGING STORAGE
  (
    PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
COMMENT ON TABLE DIR_ADDRESS
IS
  'Direcciones' ;
  COMMENT ON COLUMN DIR_ADDRESS.ADDRESS_ID
IS
  'Identificador unico de direcciones' ;
  COMMENT ON COLUMN DIR_ADDRESS.FORMAT
IS
  'Indicador de formato (ESPANA - 1, COLOMBIA - 2 ...)' ;
CREATE INDEX DIR_ADDRESS_ID1 ON DIR_ADDRESS
  (
    ADDRESS_ID ASC
  ) TABLESPACE PEOPLE PCTFREE 10 STORAGE
  (
    PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
ALTER TABLE DIR_ADDRESS ADD CONSTRAINT DIR_ADDRESS_PK PRIMARY KEY (
ADDRESS_ID ) ;
-- *************************************** ADDRESS *************************************
COMMIT;

ALTER TABLE PER_CONTACT ADD CONSTRAINT PER_CONTACT_PK PRIMARY KEY ( PER_CONTACT_ID ) ;

ALTER TABLE PER_CONTACT ADD CONSTRAINT PER_CONTACT_FK1 FOREIGN KEY ( ADDRESS_ID ) REFERENCES DIR_ADDRESS ( ADDRESS_ID ) NOT DEFERRABLE ;

ALTER TABLE PER_CONTACT ADD CONSTRAINT PER_CONTACT_FK2 FOREIGN KEY ( PERSON_DETAIL_ID ) REFERENCES PER_PERSON_DETAIL ( PERSON_DETAIL_ID ) NOT DEFERRABLE ;

ALTER TABLE PER_CONTACT ADD CONSTRAINT PER_CONTACT_FK3 FOREIGN KEY ( CONTACT_TYPE_ID ) REFERENCES PER_CONTACT_TYPE ( CONTACT_TYPE_ID ) NOT DEFERRABLE ;
COMMIT;