--------------------------------------------------------
--  Sequence for Table CONTACT
--------------------------------------------------------

CREATE SEQUENCE SEQ_CONTACT START WITH 1 MAXVALUE 9999999999 MINVALUE 1 INCREMENT BY 1 NOCYCLE NOCACHE NOORDER;
--------------------------------------------------------
--  DDL for Table CONTACT
--------------------------------------------------------
CREATE TABLE PER_CONTACT
  (
    ID_PER_CONTACT  NUMBER (19) NOT NULL ,
    ID_PERSON_DETAIL   NUMBER (19) NOT NULL ,
    ID_CONTACT_TYPE NUMBER (19) NOT NULL ,
    ID_ADDRESS     NUMBER (19) ,
    VALUE_CONTACT   VARCHAR2 (100 CHAR) NOT NULL
  )    PCTFREE 10 PCTUSED 40 TABLESPACE PEOPLE LOGGING STORAGE
  (
    PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;

COMMENT ON TABLE PER_CONTACT
IS
  'CONTACTs de la persona' ;
  COMMENT ON COLUMN PER_CONTACT.ID_PER_CONTACT
IS
  'Identificador de CONTACTs' ;
  COMMENT ON COLUMN PER_CONTACT.ID_PERSON_DETAIL
IS
  'Identificador de persona asociada al CONTACT' ;
  COMMENT ON COLUMN PER_CONTACT.ID_CONTACT_TYPE
IS
  'Tipo de CONTACT (1-Telefono, 2-Fax, 3-E-mail)' ;
  COMMENT ON COLUMN PER_CONTACT.ID_ADDRESS
IS
  'Identificador de ADDRESS asociado al CONTACT' ;
  COMMENT ON COLUMN PER_CONTACT.VALUE_CONTACT
IS
  'Descripcion del CONTACT' ;
CREATE INDEX PER_CONTACT_ID1 ON PER_CONTACT
  (
    ID_ADDRESS ASC
  )  TABLESPACE PEOPLE PCTFREE 10 STORAGE
  (
    PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
CREATE INDEX PER_CONTACT_ID2 ON PER_CONTACT
  (
    ID_PERSON_DETAIL ASC
  )  TABLESPACE PEOPLE PCTFREE 10 STORAGE
  (
    PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
CREATE INDEX PER_CONTACT_ID3 ON PER_CONTACT
  (
    ID_CONTACT_TYPE ASC
  )  TABLESPACE PEOPLE PCTFREE 10 STORAGE
  (
    PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
CREATE INDEX PER_CONTACT_ID4 ON PER_CONTACT
  (
    ID_PER_CONTACT ASC
  )  TABLESPACE PEOPLE PCTFREE 10 STORAGE
  (
    PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;

-- *************************************** ADDRESS *************************************
CREATE
  TABLE DIR_ADDRESS
  (
    ID_ADDRESS NUMBER (19) NOT NULL ,
    FORMAT      VARCHAR2 (50 CHAR) NOT NULL
  )  PCTFREE 10 PCTUSED 40 TABLESPACE PEOPLE LOGGING STORAGE
  (
    PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
COMMENT ON TABLE DIR_ADDRESS
IS
  'Direcciones' ;
  COMMENT ON COLUMN DIR_ADDRESS.ID_ADDRESS
IS
  'Identificador unico de direcciones' ;
  COMMENT ON COLUMN DIR_ADDRESS.FORMAT
IS
  'Indicador de formato (ESPANA - 1, COLOMBIA - 2 ...)' ;
CREATE INDEX DIR_ADDRESS_ID1 ON DIR_ADDRESS
  (
    ID_ADDRESS ASC
  ) TABLESPACE PEOPLE PCTFREE 10 STORAGE
  (
    PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
ALTER TABLE DIR_ADDRESS ADD CONSTRAINT DIR_ADDRESS_PK PRIMARY KEY (
ID_ADDRESS ) ;
-- *************************************** ADDRESS *************************************
COMMIT;

ALTER TABLE PER_CONTACT ADD CONSTRAINT PER_CONTACT_PK PRIMARY KEY ( ID_PER_CONTACT ) ;

ALTER TABLE PER_CONTACT ADD CONSTRAINT PER_CONTACT_FK1 FOREIGN KEY ( ID_ADDRESS ) REFERENCES DIR_ADDRESS ( ID_ADDRESS ) NOT DEFERRABLE ;

ALTER TABLE PER_CONTACT ADD CONSTRAINT PER_CONTACT_FK2 FOREIGN KEY ( ID_PERSON_DETAIL ) REFERENCES PER_PERSON_DETAIL ( PERSON_DETAIL_ID ) NOT DEFERRABLE ;

ALTER TABLE PER_CONTACT ADD CONSTRAINT PER_CONTACT_FK3 FOREIGN KEY ( ID_CONTACT_TYPE ) REFERENCES PER_CONTACT_TYPE ( CONTACT_TYPE_ID ) NOT DEFERRABLE ;
COMMIT;