-- Start of DDL Script for Sequence SYSTEM.SEQ_PER_PUBLIC_PERSON
-- Generated 27-feb.-2018 11:45:17 from SYSTEM@XE

CREATE SEQUENCE seq_per_public_person
  INCREMENT BY 1
  START WITH 13
  MINVALUE 1
  MAXVALUE 9999999999
  NOCYCLE
  NOORDER
  NOCACHE
/


-- End of DDL Script for Sequence SYSTEM.SEQ_PER_PUBLIC_PERSON
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--personasPublicas.sql------------------------------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE per_PUBLIC_PERSON
(
  ID_PER_PUBLIC_PERSON  NUMBER (19) NOT NULL ,
  ID_TYPE_PUBLIC_PERSON NUMBER (19) NOT NULL ,
  ID_PERSON             NUMBER (19) NOT NULL
)
TABLESPACE PEOPLE LOGGING ;
COMMENT ON COLUMN per_PUBLIC_PERSON.ID_PER_PUBLIC_PERSON
IS
'Identificador unico de la relacion Persona con Tipo de persona publica' ;
COMMENT ON COLUMN per_PUBLIC_PERSON.ID_TYPE_PUBLIC_PERSON
IS
'Tipo de persona publica' ;
COMMENT ON COLUMN per_PUBLIC_PERSON.ID_PERSON
IS
'Identificador de la Persona' ;
CREATE INDEX PER_PUBLIC_PERSON_ID1 ON PER_PUBLIC_PERSON
(
  ID_PER_PUBLIC_PERSON ASC
)
TABLESPACE PEOPLE LOGGING ;
CREATE INDEX PER_PUBLIC_PERSON_ID2 ON PER_PUBLIC_PERSON
(
  ID_TYPE_PUBLIC_PERSON ASC
)
TABLESPACE PEOPLE LOGGING ;
CREATE INDEX PER_PUBLIC_PERSON_ID3 ON PER_PUBLIC_PERSON
(
  ID_PERSON ASC
)
TABLESPACE PEOPLE LOGGING ;
CREATE INDEX PER_PUBLIC_PERSON_ID4 ON PER_PUBLIC_PERSON
(
  ID_TYPE_PUBLIC_PERSON ASC ,
  ID_PERSON ASC
)
TABLESPACE PEOPLE LOGGING ;
ALTER TABLE PER_PUBLIC_PERSON ADD CONSTRAINT PER_PUBLIC_PERSON_PK PRIMARY KEY ( ID_PER_PUBLIC_PERSON ) ;
ALTER TABLE PER_PUBLIC_PERSON ADD CONSTRAINT PER_PUBLIC_PERSON_FK1 FOREIGN KEY ( ID_TYPE_PUBLIC_PERSON ) REFERENCES PER_TYPE_PUBLIC_PERSON ( ID_TYPE_PUBLIC_PERSON ) NOT DEFERRABLE ;
ALTER TABLE PER_PUBLIC_PERSON ADD CONSTRAINT PER_PUBLIC_PERSON_FK2 FOREIGN KEY ( ID_PERSON ) REFERENCES PER_PERSONA ( ID_PERSON ) NOT DEFERRABLE ;
CREATE SEQUENCE SEQ_PER_PUBLIC_PERSON INCREMENT BY 1 MAXVALUE 9999999999 MINVALUE 1 NOCACHE ;
