-- DROP BANK ****************************************************************
DROP INDEX PER_BANK_ACCOUNT_ID1;
DROP INDEX PER_BANK_ACCOUNT_ID2;
DROP INDEX PER_BANK_ACCOUNT_ID3;
DROP INDEX PER_BANK_ACCOUNT_ID4;

DROP SEQUENCE SEQ_BANK;
DROP SEQUENCE SEQ_CLASIFICATION_ACCOUNT;
DROP SEQUENCE SEQ_BANK_ACCOUNT;
DROP SEQUENCE SEQ_TYPE_ACCOUNT;

DROP TABLE PER_BANK CASCADE CONSTRAINTS;
DROP TABLE PER_BANK_CARD CASCADE CONSTRAINTS;
DROP TABLE PER_CLASIFICATION_ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE PER_BANK_ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE PER_TYPE_ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE PER_BANK CASCADE CONSTRAINTS;
DROP TABLE PER_CARD_TYPE CASCADE CONSTRAINTS;

-- DROP BANK END ****************************************************************
COMMIT;
