-- DROP BANK ****************************************************************
DROP CONSTRAINT PER_BANK_PK;
DROP CONSTRAINT PER_BANK_UK1;
DROP CONSTRAINT PER_CLASSIFICATION_ACCOUNT_PK;

DROP INDEX PER_BANK_ACCOUNT_ID1;
DROP INDEX PER_BANK_ACCOUNT_ID2;
DROP INDEX PER_BANK_ACCOUNT_ID3;
DROP INDEX PER_BANK_ACCOUNT_ID4;

DROP CONSTRAINT PER_BANK_ACCOUNT_PK;
DROP CONSTRAINT PER_BANK_ACCOUNT_UK1;
DROP CONSTRAINT PER_TYPE_ACCOUNT_PK;
DROP CONSTRAINT PER_BANK_ACCOUNT_FK1;
DROP CONSTRAINT PER_BANK_ACCOUNT_FK2;
DROP CONSTRAINT PER_BANK_ACCOUNT_FK3;
DROP CONSTRAINT PER_BANK_ACCOUNT_FK4;

DROP SEQUENCE SEQ_BANK;
DROP SEQUENCE SEQ_CLASSIFICATION_ACCOUNT;
DROP SEQUENCE SEQ_BANK_ACCOUNT;
DROP SEQUENCE SEQ_TYPE_ACCOUNT;
 
DROP TABLE PER_BANK;
DROP TABLE PER_CLASSIFICATION_ACCOUNT;
DROP TABLE PER_BANK_ACCOUNT;
DROP TABLE PER_TYPE_ACCOUNT;
DROP TABLE PER_BANK;
DROP TABLE PER_BANK;
DROP TABLE PER_BANK;
-- DROP BANK END ****************************************************************
COMMIT;

-- DROP ********************* BANK CARD ************************************************************
-- Indexes
DROP INDEX PER_BANK_ACCOUNT_ID1;
DROP INDEX PER_BANK_ACCOUNT_ID2;
DROP INDEX PER_BANK_ACCOUNT_ID3;
DROP INDEX PER_BANK_ACCOUNT_ID4;

DROP INDEX PER_BANK_CARD_ID1
DROP INDEX PER_BANK_CARD_ID2
DROP INDEX PER_BANK_CARD_ID3

-- Constraints
DROP CONSTRAINT PER_BANK_ACCOUNT_PK;
DROP CONSTRAINT PER_BANK_ACCOUNT_UK1;
DROP CONSTRAINT PER_CLASSIFICATION_ACCOUNT_PK;

DROP CONSTRAINT PER_TYPE_ACCOUNT_PK;
DROP CONSTRAINT PER_BANK_ACCOUNT_FK1;
DROP CONSTRAINT PER_BANK_ACCOUNT_FK2;
DROP CONSTRAINT PER_BANK_ACCOUNT_FK3;
DROP CONSTRAINT PER_BANK_ACCOUNT_FK4;

DROP CONSTRAINT PER_BANK_CARD_BANCARIA_PK;
DROP CONSTRAINT PER_BANK_CARD_UK1;

DROP CONSTRAINT PER_CARD_TYPE_PK;
DROP CONSTRAINT PER_BANK_CARD_FK1;
DROP CONSTRAINT PER_BANK_CARD_FK2;
DROP CONSTRAINT PER_BANK_CARD_FK3;

-- Secuences
DROP SEQUENCE SEQ_BANK;
DROP SEQUENCE SEQ_CLASSIFICATION_ACCOUNT;
DROP SEQUENCE SEQ_BANK_ACCOUNT;
DROP SEQUENCE SEQ_TYPE_ACCOUNT;

DROP SEQUENCE SEQ_BANK_CARD;
DROP SEQUENCE SEQ_CARD_TYPE;

DROP TABLE PER_BANK;
DROP TABLE PER_BANK_ACCOUNT;
DROP TABLE PER_TYPE_ACCOUNT;
DROP TABLE PER_BANK_CARD;
DROP TABLE PER_CARD_TYPE;
-- DROP END ********************* BANK CARD ************************************************************
COMMIT;